### PR TITLE
PULSSI-951

### PR DESCRIPTION
**Pull request by timyllym**
Load Pulssi frame if Grafana is not inside Iframe

### CODE REVIEW

**Comment by timyllym** [comment]
Currently there are only those three parameters needed between Pulssi frontend and Grafana: dashboard, breadcrumb and orgId. There is a possibility that this changes at some point.

**Comment by kompa3** [comment]
Actually, good point from Sami. We are often using template variables as part of url
http://docs.grafana.org/reference/templating/#url-state

**Comment by kompa3** [comment]
We also might like to use from and to url parameters in drilldown links, to set a templated dashboard to use the same time range as the source (top-most) dashboard.

**Comment by timyllym** [comment]
Ok. Then we probably need to pass all the parameters as such between Grafana and Pulssi frontend.

**Pull request merged**
